---
- name: update apt cache
  apt:
    update_cache: yes
    force: true

- name: restart docker
  become: yes
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes

