---
  - name: Install docker requirements
    notify: update apt cache
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - curl
      - ca-certificates

  - name: create keyrings directory if it doesn't exist and set the permissions
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: touch
      mode: '0755'

  - name: Download docker GPG key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'
      
  - name: Add Docker APT source.list
    copy:
      dest: /etc/apt/sources.list.d/docker.list
      content: |
        deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
      mode: '0644'
    notify: update apt cache

  - name: Install the Docker packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin