---
- name: Ensure systemd-resolved is enabled and started
  become: yes
  systemd:
    name: systemd-resolved
    enabled: yes
    state: started
  tags:
    - debian
    - docker
    - dns

- name: Deploy systemd-resolved configuration
  become: yes
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart systemd-resolved
  tags:
    - debian
    - docker
    - dns

- name: Ensure /etc/resolv.conf is symlinked to stub-resolv.conf
  become: yes
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  tags:
    - debian
    - docker
    - dns